language: node_js
node_js:
- '8'
# sude: required
# services:
#   - docker
cache:
  yarn: true
  directories:
    - node_modules
after_success:
- yarn coverage
# deploy:
#   provider: npm
#   email: toxictoxer@gmail.com
#   on:
#     tags: true